### ISSUE TITLE
switch mappings

### ISSUE THREAD

**Issue by wyntrblue** [AndrewFarley/Taranis-XLite-Q7-Lua-Dashboard#1]
hi Dude, really like the telem screen. its exactly whats needed. However you have pre defined the mapping for the armed and flight modes. 

can you detail how to change the mappings in the script so that we can change them to other mappings if were using something different. 

for example you have arm on SA but i use SC
and i use SA for flight mode.

im also having an issue with the timer, how do you trigger the timer to start? is it a countdown or a count up?

**Comment by wyntrblue** [comment]
Ok I really should have just read your excellently commented code!

Switch mappings are sorted. 

Still not sure what to do with the timers tho

**Comment by AndrewFarley** [comment]
Ahh, @wyntrblue sorry I didn't see your message, I didn't have notifications on this repo!

I'll update the readme when I can... but you'll want to go to your "setup" page of your model, right under where it says "model name" it will say "timer1".  Select that, and then choose which logical switch and position you want it to turn on on.  Then select how long of a timer you want.  I usually set it at like 3min for my whoops.  It should look like this...

![image from ios 3](https://user-images.githubusercontent.com/470163/53410715-d9aede00-39c4-11e9-8426-d1fb85bbd26d.jpg)
