### ISSUE TITLE
Will the remote control with 480*272 screen pixels be supported in the future?

### ISSUE THREAD

**Issue by hz89377361** [AndrewFarley/Taranis-XLite-Q7-Lua-Dashboard#12]
Will the remote control with 480*272 screen pixels be supported in the future?

**Comment by AndrewFarley** [comment]
@hz89377361 Likely no.  But the script is pretty easy to edit to move things around a bit.  It wouldn’t be hard to edit I know some other folks have made edits to this for their own handsets.  If you dive into making it support an alternate screen size please share it with me so everyone can use it.

btw what transmitter has that size?

**Comment by hz89377361** [comment]
For example, jumper t16/t18，radiomaster tx16s，frsky x10/x12s
