### ISSUE TITLE
Logical switch

### ISSUE THREAD

**Issue by ssombra** [AndrewFarley/Taranis-XLite-Q7-Lua-Dashboard#2]
It looks great! 
I use a logical switch to arm my quads, do you know how I can refer to a logical switch (logical switch 2) instead of a physical switch in your code?:
armed = getValue('sa')

thanks

**Comment by AndrewFarley** [comment]
@ssombra I haven't done it off hand but it looks like you're looking for...

`model.getLogicalSwitch()` from [OpenTX Lua Guide](https://docs.google.com/document/d/1ILh9lSW4d05qJD2rSKxep0WnJUfNCcAPCafKZeESweE/mobilebasic?pli=1#h.5xx8zs3tokph)

You would probably change the line...

`armed = getValue('sa')`

to something like...

`armed = model.getLogicalSwitch("L1")`

I've never used or programmed logical switches, if you figure it out, please feel to share how, and I can add it as a comment to the code and the README so others can use it as well.  Cheers!

**Comment by ssombra** [comment]
Hi AndrewFarley. I did figure it out, the names of the logical switches start with "ls" followed by the number so in your script and for the logical switch 2 it would be:
`armed = getValue('ls2')`
it works great, thanks for this excellent script.
