### ISSUE TITLE
Timer

### ISSUE THREAD

**Issue by Outbrdman** [AndrewFarley/Taranis-XLite-Q7-Lua-Dashboard#4]
Thanks for a great Lua script! Could you please explain how i can invert the timer? I have inverted the arming function and the flight modes to match up with my transmitter, but now the timer runs when disarmed and stops when i arm, and i havent been able to solve it. Thanks!

**Comment by AndrewFarley** [comment]
Go into your timer settings and configure what enables the timer.  This is on the second page of your model configuration, right at the top.  :)
