### ISSUE TITLE
Mode Classification

### ISSUE THREAD

**Issue by FPVScrub** [AndrewFarley/Taranis-XLite-Q7-Lua-Dashboard#5]
This isn't an "issue" per say, more of request from someone that doesn't know what they are doing. 

I want to change the wording order when I use my "mode" switch. The current modes, from what I recall, are Acro, Horizon and Air mode. I would like to change mine to Angle mode, Air mode, Acro mode but I just can't figure how to do so. 

I've changed my battery voltage values and switch assignments without an issue. 

In the event it matters: I'm using a Q-X7S running OpenTX 2.2.3. Unbelievable work btw, this Lua Script is amazing.

**Comment by AndrewFarley** [comment]
The source code is very easy to understand.  If you opened the .lua script in a text editor on your computer, and search for the word "Horizon" you would instantly find it....

https://github.com/AndrewFarley/Taranis-XLite-Q7-Lua-Dashboard/blob/master/farl.lua#L462

Then just replace the words in that function with whatever words you want.  Make it say Air, Angle, Rate, Auto-level, whatever you want.

Enjoy!

**Comment by FPVScrub** [comment]
Thank you!!
