### ISSUE TITLE
Fly Timer

### ISSUE THREAD

**Issue by Oxize** [AndrewFarley/Taranis-XLite-Q7-Lua-Dashboard#9]
The Fly timer doesnt work. If i put a timer under my model, you see an timer on the normal screen, but not on the lua script. How is the Fly Timer related to something? How to configure this?

**Comment by Oxize** [comment]
![u6nlwjWh](https://user-images.githubusercontent.com/3933702/85791434-1b26d900-b732-11ea-927d-93d13f188b09.jpg)
![JvCykzqh](https://user-images.githubusercontent.com/3933702/85791438-1bbf6f80-b732-11ea-8457-d3397bf961e2.jpg)
![u1t54Rxh](https://user-images.githubusercontent.com/3933702/85791440-1c580600-b732-11ea-8b5e-b05df8cc7f97.jpg)

**Comment by AndrewFarley** [comment]
You have to google the topic of how fly timers work.  In the "Setup" interface you need to set the time of how long you want the timer to go for.  And then typically you set a "reset" button as well, so you can in-between your batteries reset this to 0.  I usually set that on a toggle-switch.

**Comment by AndrewFarley** [comment]
@Oxize ^^

**Comment by Oxize** [comment]
@AndrewFarley 
The first picture shows that (and have special function for reset). In 2nd picture you have a Fly Timer in the lower right corner. Why doesnt this one work?

**Comment by AndrewFarley** [comment]
@Oxize Yeah, but your first screenshot shows you have the timer set to 00:00?

**Comment by AndrewFarley** [comment]
Oh sorry I was looking at your second timer, that's weird.  One sec let me grab my handset

**Comment by AndrewFarley** [comment]
Yeah, your timer looks good man.  I don't know, you'd have to jump into the code.  What version of OpenTX is on your handset?
![Image from iOS (32)](https://user-images.githubusercontent.com/470163/85804447-c15bf880-b79d-11ea-8305-ced48da76e2c.jpg)

**Comment by Oxize** [comment]
2.3.0 (ac8b056b)
eepr: 219

updating to 2.3.9 now.

**Comment by Oxize** [comment]
@AndrewFarley
If i dig into the code, its stating to timerleft something.

But i want this one working.
![image](https://user-images.githubusercontent.com/3933702/85860475-27a54300-b7bf-11ea-9572-7c505c5049f5.png)

**Comment by Oxize** [comment]
Nevermind. Ive putted the wrong timer on the reciever. Working now.
